set -x
./js_run.sh hello
./js_run.sh while
./js_run.sh sum
./js_run.sh fn
./js_run.sh for
./js_run.sh if
./js_run.sh array
./js_run.sh matrix
./js_run.sh mt
./js_run.sh global
./js_run.sh obj
./js_run.sh import
./js_run.sh sha256
./js_run.sh sqlite
# ./js_run.sh python
./js_run.sh map
./js_run.sh class
./js_run.sh try