global.sin = Math.sin
global.cos = Math.cos
global.tan = Math.tan
global.asin= Math.asin
global.acos= Math.acos
global.atan= Math.atan
global.sinh= Math.sinh
global.cosh= Math.cosh
global.tanh= Math.tanh
global.exp = Math.exp
global.sqrt= Math.sqrt
global.pow = Math.pow
global.abs = Math.abs
global.round = Math.round
global.floor = Math.floor
global.ceil = Math.ceil
global.random = Math.random
global.E = Math.E
global.PI = Math.PI
global.ln = Math.log
global.log2 = Math.log2
global.log10 = Math.log10
